turicas/covid19-br

README.md

`README.md` atualizado com _clipping_ coletados na issue #39
/refs #39

Atualização do clipping

---

README.md
api.md
report.py

Adiciona documentação da API

---

README.md

- adicionada análise
- adicionado notícia do jornal Metrópole

Atualizando Clipping

---

api.md

Adiciona exemplos na documentação da API

---

bot/url_spider.py

limita notificacoes do bot aos voluntarios

---

README.md

Dashboard para monitoramento do COVID-19 no Brazil por estado.

Dashboard do Brasil sobre COVID-19 usado a API Brasil.io

---

.dockerignore
Dockerfile
Makefile
README.md

a ideia é simplificar instalação para quem adota o Docker como solução
em breve pode ser até possível publicar o pacote no github packages

dockerizando a aplicação

---

.github/workflows/goodtables.yaml
.github/workflows/pytest.yaml
Dockerfile
Makefile
validate.sh

O CI do Goodtables passa a fazer o download dos arquivos publicados no brasil.io, ao invés de coleta-los durante o build do CI, e agora será agendado para executar diariamente às 01:00am.
Isso evita de fazer o build sempre que houver commit ou PR que não necessariamente irá gerar novos dados.

Separa job CI do Goodtables

---

api.md

Remove o path ..."/dados/"... e adiciona ..."/data"

Atualiza url's da API

---

recomendacoes.md

um CSV de exemplo foi adicionado, além de informar um padrão para o campo data (ISO 8061)

doc: adiciona CSV de exemplo

---

CONTRIBUTING.md

remove referencia às planilhas do Google Sheets onde eram feitas as
atualizações de dados dos Estados e adiciona informações sobre o novo
sistema de coleta de dados
/refs #128

doc : adiciona informação sobre novo sistema

---

web/spiders/__init__.py
web/spiders/spider_ce.py

Implementa spider baseado na API JSON do http://integrasus.saude.ce.gov.br/
/refs #15 #130

Adiciona spider para CE

---

clipping.md

Um chatbot com inteligência artificial desenvolvido pela SINFO/UFRN para te responder questões sobre a COVID-19 e os seus efeitos.

Adição do projeto Chicó - SINFO/UFRN

---

clipping.md

Adicionando notícia do G1 rs relacionada ao grupo CovidMetrika e link com site e repositório do grupo. Utilizamos os dados do brasil.io sobre a covid-19 no dashboard do RS e no do Brasil.

Adicionando notícias e projetos do CovidMetrika

---

clipping.md

Acrescenta:
* visualização por @wcota
* ferramenta para carregar os dados no Kibana/ElasticSearch por @dpereira

acrescenta links no Clipping (visualização e ferramenta)

---

clipping.md

corrige o nome do jornal

---

consolida.py
report.py

Revisar primeiro https://github.com/turicas/brasil.io/pull/319

Altera formato de download de dados do Brasil.IO

---

README.en.md
README.md
validate.sh

https://github.com/danielfsbarreto/covid19-br/runs/814158059?check_suite_focus=true#step:3:917
Action falhando, mas agora pelo motivo certo: infelizmente há diversas violações que precisam ser resolvidas, seja através de ajustes no dataset em si ou no `datapackage.json`.

Fix goodtables action

---

clipping.md

Adicionei outro artigo científico que publiquei na ScienceDirect utilizando os dados da API.

Update Publicacoes cientificas em clipping.md

---

consolida.py
obitos_convert.py
obitos_spider.py
obitos_totais_spider.py
report.py
web/app.py
web/run_spider.py
web/spiders/__init__.py
web/spiders/spider_ce.py
web/spiders/spider_pa.py

Pull request em andamento, resolve a issue #189 
Tarefas:

WIP Fix/obitos spider
